### ISSUE TITLE
Title might not really change when using cmd+arrow key

### ISSUE THREAD

**Issue by link-ding** [jplattel/open-note-to-window-title#13]
I am currently using Keyboard maestro. There is a trigger "when the window's title change". If I click the link or click the file from the side bar, the trigger will work. However, If I use command + arrow key to navigate the file, it will not triggering the macro. It might not be the issue of this plugin cos I download the old version of this plugin and it still have this problem. Hopefully you can give some suggestion to solve this problem.

Thanks in advance.

**Comment by link-ding** [comment]
https://user-images.githubusercontent.com/49264539/130347808-33f0c464-e67b-47a2-97ae-269bdb0cd5b3.mov

This video might be more clear to explain the issue.
I first at "algorithm design" file and get the current file window title is correct. Then I use cmd+left arrow key to back to "Computer Science" file page and get current file again. It still show the window title is the last page's title.

**Comment by luckman212** [comment]
Sorry, but not quite sure what's going on in your video... maybe some voiceover would help, or just a written out step-by-step. When I try navigating using e.g. ⌘cmd ← the title is updating on my system.

**Comment by jplattel** [comment]
It seems like the title is updating correctly on the window, except that Keyboard Meastro is not picking it up correctly. 

As a user of Keyboard Meastro myself I can test if this is something on Keyboard Meastro's side, are you using the `%WindowName%1%` variable?

**Comment by link-ding** [comment]
> It seems like the title is updating correctly on the window, except that Keyboard Meastro is not picking it up correctly.
> 
> As a user of Keyboard Meastro myself I can test if this is something on Keyboard Meastro's side, are you using the `%WindowName%1%` variable?

Yes, this is what I am talking about. The real trigger I use for the macro is "focused window's title changed". In the video, I just show the window title by using "%WindowName%1%".

**Comment by jplattel** [comment]
Alright, I'm trying to replicate the bug, but it seems to work properly for me, this is the macro I've been using: 

<img width="567" alt="Screenshot 2021-08-23 at 08 59 01" src="https://user-images.githubusercontent.com/517775/130408772-047e626f-9f80-409b-9394-8875e391f9b3.png">

I'm using Keyboard Meastro 9.0.6. What version are you using?

**Comment by link-ding** [comment]
> Alright, I'm trying to replicate the bug, but it seems to work properly for me, this is the macro I've been using:
> 
> <img alt="Screenshot 2021-08-23 at 08 59 01" width="567" src="https://user-images.githubusercontent.com/517775/130408772-047e626f-9f80-409b-9394-8875e391f9b3.png">
> 
> I'm using Keyboard Meastro 9.0.6. What version are you using?

I am using keyboard maestro 9.2
![image](https://user-images.githubusercontent.com/49264539/130426376-6156ca16-0e8f-4b54-9af1-2bce75fb995d.png)

**Comment by jplattel** [comment]
Mmh, strange I just can't replicate it with my version of KM, since it's a paid upgrade I'm not yet updating to 9.2, thus I'm unable to test it with that version.

As for the back/forward triggers, I've tried it with both the shortcuts and that works for me. Are you using any other plugins like Sliding panes or anything that might modify the focus?

**Comment by link-ding** [comment]
I try to create a new vault and only install this plugin to show the title but still have this issue.

https://user-images.githubusercontent.com/49264539/130721579-9fc5a75b-df7b-4431-898e-dcfd9da9c2b4.mov

**Comment by link-ding** [comment]
I asked my friend whose keyboard maestro's version is 9.0.5 to replicate the issue and he has this issue as well. If it is possible can you please record a video to show me how you replicate it?

https://user-images.githubusercontent.com/49264539/130723124-f82454bf-a526-4779-8ed8-3cb2f2e5e576.mp4

**Comment by link-ding** [comment]
> Mmh, strange I just can't replicate it with my version of KM, since it's a paid upgrade I'm not yet updating to 9.2, thus I'm unable to test it with that version.
> 
> As for the back/forward triggers, I've tried it with both the shortcuts and that works for me. Are you using any other plugins like Sliding panes or anything that might modify the focus?

Could you please show me how to replicate the issue? I've been really struggling with this problem for a long time.

**Comment by jplattel** [comment]
I've just released [0.3.1](https://github.com/jplattel/open-note-to-window-title/releases/tag/0.3.1). I think that's the reason it worked on my computer, since I was working with newly committed code. 

Could you let me know if this new version works for you? Thanks!

**Comment by link-ding** [comment]
Thanks for replying, I update to latest version plugin and reopen obsidian but it still does not work.
